# Application name
spring:
  application:
    name: registry
# Server port
server:
  port: 8761
# This microservice is not a client, so the value is false
# microservices registration url
eureka:
  client:
    service-url:
      register-with-eureka: false
      fetch-registry: false
      defaultZone: http://localhost:8761/eureka
# disabling unnecessary logging
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
  # logging pattern
  pattern.console: "%C{.1} [%-5level] %d{HH:mm:ss} - %msg%n"
